/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py:335: RuntimeWarning: invalid value encountered in subtract
  lnpdiff = (self.dim - 1.) * np.log(zz) + newlnprob - lnprob0
/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py:336: RuntimeWarning: invalid value encountered in greater
  accept = (lnpdiff > np.log(self._random.rand(len(lnpdiff))))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
Traceback (most recent call last):
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 148, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 127, in lnlike
    res, sigma, success = residual(pars)
  File "lf_fitter.py", line 102, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_shen12_lf_data.py", line 10, in load_shen12_lf_data
    data = np.genfromtxt(filename,names=["z_min", "z_max", "z_mid", "magz2", "logPhi", "elogPhi"])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1713, in genfromtxt
    first_line = _decode_line(next(fhd), encoding)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/codecs.py", line 314, in decode
MemoryError
Traceback (most recent call last):
  File "lf_fitter.py", line 164, in <module>
    pool.wait()
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/mpi_pool.py", line 117, in wait
    result = self.function(task)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 148, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 127, in lnlike
    res, sigma, success = residual(pars)
  File "lf_fitter.py", line 102, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_shen12_lf_data.py", line 10, in load_shen12_lf_data
    data = np.genfromtxt(filename,names=["z_min", "z_max", "z_mid", "magz2", "logPhi", "elogPhi"])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1713, in genfromtxt
    first_line = _decode_line(next(fhd), encoding)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
MemoryError
Traceback (most recent call last):
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 148, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 127, in lnlike
    res, sigma, success = residual(pars)
  File "lf_fitter.py", line 102, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/newx_load_aird10_lf_data.py", line 11, in load_aird10_lf_data
    data = np.genfromtxt(filename,names=True)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "lf_fitter.py", line 164, in <module>
    pool.wait()
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/mpi_pool.py", line 117, in wait
    result = self.function(task)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 148, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 127, in lnlike
    res, sigma, success = residual(pars)
  File "lf_fitter.py", line 102, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/newx_load_aird10_lf_data.py", line 11, in load_aird10_lf_data
    data = np.genfromtxt(filename,names=True)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 148, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 127, in lnlike
    res, sigma, success = residual(pars)
  File "lf_fitter.py", line 102, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_ross13_lf_data.py", line 29, in load_ross13_s82_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1713, in genfromtxt
    first_line = _decode_line(next(fhd), encoding)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
MemoryError
Traceback (most recent call last):
  File "lf_fitter.py", line 164, in <module>
    pool.wait()
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/mpi_pool.py", line 117, in wait
    result = self.function(task)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 148, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 127, in lnlike
    res, sigma, success = residual(pars)
  File "lf_fitter.py", line 102, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_ross13_lf_data.py", line 29, in load_ross13_s82_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1713, in genfromtxt
    first_line = _decode_line(next(fhd), encoding)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
MemoryError
Traceback (most recent call last):
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 148, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 127, in lnlike
    res, sigma, success = residual(pars)
  File "lf_fitter.py", line 102, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/newx_load_aird10_lf_data.py", line 11, in load_aird10_lf_data
    data = np.genfromtxt(filename,names=True)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "lf_fitter.py", line 164, in <module>
    pool.wait()
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/mpi_pool.py", line 117, in wait
    result = self.function(task)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 148, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 127, in lnlike
    res, sigma, success = residual(pars)
  File "lf_fitter.py", line 102, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/newx_load_aird10_lf_data.py", line 11, in load_aird10_lf_data
    data = np.genfromtxt(filename,names=True)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 148, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 127, in lnlike
    res, sigma, success = residual(pars)
  File "lf_fitter.py", line 102, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/newx_load_aird10_lf_data.py", line 11, in load_aird10_lf_data
    data = np.genfromtxt(filename,names=True)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "lf_fitter.py", line 164, in <module>
    pool.wait()
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/mpi_pool.py", line 117, in wait
    result = self.function(task)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 148, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 127, in lnlike
    res, sigma, success = residual(pars)
  File "lf_fitter.py", line 102, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/newx_load_aird10_lf_data.py", line 11, in load_aird10_lf_data
    data = np.genfromtxt(filename,names=True)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 148, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 127, in lnlike
    res, sigma, success = residual(pars)
  File "lf_fitter.py", line 102, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/newx_load_aird10_lf_data.py", line 11, in load_aird10_lf_data
    data = np.genfromtxt(filename,names=True)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "lf_fitter.py", line 164, in <module>
    pool.wait()
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/mpi_pool.py", line 117, in wait
    result = self.function(task)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 148, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 127, in lnlike
    res, sigma, success = residual(pars)
  File "lf_fitter.py", line 102, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/newx_load_aird10_lf_data.py", line 11, in load_aird10_lf_data
    data = np.genfromtxt(filename,names=True)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
slurmstepd: error: *** JOB 138310 ON wheeler045 CANCELLED AT 2019-03-08T20:24:00 ***
