Traceback (most recent call last):
  File "lf_fitter.py", line 26, in <module>
    c_extenstion = CDLL(homepath+'codes/c_lib/convolve.so')
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/ctypes/__init__.py", line 366, in __init__
Traceback (most recent call last):
  File "lf_fitter.py", line 26, in <module>
    c_extenstion = CDLL(homepath+'codes/c_lib/convolve.so')
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/ctypes/__init__.py", line 366, in __init__
Traceback (most recent call last):
  File "lf_fitter.py", line 26, in <module>
    c_extenstion = CDLL(homepath+'codes/c_lib/convolve.so')
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/ctypes/__init__.py", line 366, in __init__
Traceback (most recent call last):
  File "lf_fitter.py", line 26, in <module>
    c_extenstion = CDLL(homepath+'codes/c_lib/convolve.so')
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/ctypes/__init__.py", line 366, in __init__
Traceback (most recent call last):
  File "lf_fitter.py", line 26, in <module>
    c_extenstion = CDLL(homepath+'codes/c_lib/convolve.so')
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/ctypes/__init__.py", line 366, in __init__
Traceback (most recent call last):
  File "lf_fitter.py", line 26, in <module>
    c_extenstion = CDLL(homepath+'codes/c_lib/convolve.so')
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/xuejian/works/quasarLF/git/codes/c_lib/convolve.so: cannot open shared object file: Stale file handle
    self._handle = _dlopen(self._name, mode)
OSError: /home/xuejian/works/quasarLF/git/codes/c_lib/convolve.so: cannot open shared object file: Stale file handle
    self._handle = _dlopen(self._name, mode)
OSError: /home/xuejian/works/quasarLF/git/codes/c_lib/convolve.so: cannot open shared object file: Stale file handle
    self._handle = _dlopen(self._name, mode)
OSError: /home/xuejian/works/quasarLF/git/codes/c_lib/convolve.so: cannot open shared object file: Stale file handle
    self._handle = _dlopen(self._name, mode)
    self._handle = _dlopen(self._name, mode)
OSError: /home/xuejian/works/quasarLF/git/codes/c_lib/convolve.so: cannot open shared object file: Stale file handle
OSError: /home/xuejian/works/quasarLF/git/codes/c_lib/convolve.so: cannot open shared object file: Stale file handle
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
slurmstepd: error: *** JOB 183031 ON wheeler042 CANCELLED AT 2019-07-03T14:15:32 ***
